const categories = {
  Dealership: {
    subcategories: [
      {
        label: "Cars & Bakkies",    
        attributes: [
            {
              key: "year",
              type: "select",
              label: "Year",
              placeholder: "Select year",
              required: true,
              validationMessage: "Please select a year",
              options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
              onChangeHandler: "handleYear",
            },
            {
              key: "make",
              type: "select",
              label: "Make",
              placeholder: "Select make",
              required: true,
              validationMessage: "Make is required",
              optionsSource: "mmcodeMakes",
              onChangeHandler: "handleMake",
            },
            {
              key: "model",
              type: "select",
              label: "Model",
              placeholder: "Select model",
              required: true,
              validationMessage: "Model is required",
              optionsSource: "mmcodeModels",
              onChangeHandler: "handleModel",
            },
            {
              key: "variant",
              type: "select",
              label: "Variant",
              placeholder: "Select variant",
              required: true,
              validationMessage: "Variant is required",
              optionsSource: "mmcodeVariants",
              onChangeHandler: "handleVariant",
            },
            {
              key: "mmCode",
              type: "text",
              label: "MMCode",
              placeholder: "Not available",
              disabled: true,
            },
            {
              key: "fuelType",
              type: "select",
              label: "Fuel Type",
              placeholder: "Select Fuel Type",
              required: true,
              validationMessage: "Fuel type is required",
              options: ["Petrol", "Diesel", "Hybrid", "Electric"],
            },
            {
              key: "transmission",
              type: "select",
              label: "Transmission",
              placeholder: "Select Transmission",
              required: true,
              validationMessage: "Transmission is required",
              options: ["Auto", "Manual"],
            },
            {
              key: "mileage",
              type: "number",
              label: "Mileage",
              placeholder: "Enter mileage",
              required: true,
              validationMessage: "Mileage is required",
            },
            {
              key: "colour",
              type: "select",
              label: "Colour",
              placeholder: "Select Colour",
              required: true,
              validationMessage: "Colour is required",
              optionsSource: "colors",
            },
            {
              key: "vinNr",
              type: "text",
              label: "VIN Number",
              placeholder: "Enter VIN Number",
              required: true,
              convert: "uppercase",
              validationMessage: "VIN number is required",
              validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
              regexMessage: "Invalid VIN number format (must be 17 characters)",
              mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
              inputGroup: {
                append: [
                  {
                    type: "button",
                    label: "Scan",
                    variant: "primary",
                    onClickHandler: "handleVinScan",
                  }
                ]
              }              
            },
            {
              key: "engineNr",
              type: "text",
              label: "Engine Number",
              placeholder: "Enter Engine Number",
              required: true,
              convert: "uppercase",
              validationMessage: "Engine number is required",
              minLength: 6,
              regexMessage: "Engine number must be at least 6 characters",
              mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
            },
            {
              key: "regNr",
              type: "text",
              label: "Registration Number",
              placeholder: "Enter Reg Number",
              required: true,
              convert: "uppercase",
              validationMessage: "Registration number is required",
              mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
            },
            {
              key: "stockNr",
              type: "text",
              label: "Stock Number",
              placeholder: "Enter Stock Number",
              convert: "uppercase",
            },
          ]        
      },
      {
        label: "Bikes",
        attributes: [
          {
            key: "year",
            type: "select",
            label: "Year",
            placeholder: "Select year",
            required: true,
            validationMessage: "Please select a year",
            options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
            onChangeHandler: "handleYear",
          },
          {
            key: "make",
            type: "text",
            label: "Make",
            placeholder: "Enter make",
            required: true,
            convert: "titlecase",
            validationMessage: "Make is required",
          },
          {
            key: "model",
            type: "text",
            label: "Model",
            placeholder: "Enter model",
            required: true,
            convert: "titlecase",
            validationMessage: "Model is required",
          },
          {
            key: "variant",
            type: "text",
            label: "Variant",
            placeholder: "Enter variant",
            required: true,
            convert: "titlecase",
            validationMessage: "Variant is required",
          },
          {
            key: "mmCode",
            type: "text",
            label: "MMCode",
            placeholder: "Not available",
            disabled: true,
          },
          {
            key: "fuelType",
            type: "select",
            label: "Fuel Type",
            placeholder: "Select Fuel Type",
            required: true,
            validationMessage: "Fuel type is required",
            options: ["Petrol", "Diesel", "Hybrid", "Electric"],
          },
          {
            key: "transmission",
            type: "select",
            label: "Transmission",
            placeholder: "Select Transmission",
            required: true,
            validationMessage: "Transmission is required",
            options: ["Auto", "Manual"],
          },
          {
            key: "mileage",
            type: "number",
            label: "Mileage",
            placeholder: "Enter mileage",
            required: true,
            validationMessage: "Mileage is required",
          },
          {
            key: "colour",
            type: "select",
            label: "Colour",
            placeholder: "Select Colour",
            required: true,
            validationMessage: "Colour is required",
            optionsSource: "colors",
          },
          {
            key: "vinNr",
            type: "text",
            label: "VIN Number",
            placeholder: "Enter VIN Number",
            required: true,
            convert: "uppercase",
            validationMessage: "VIN number is required",
            validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
            regexMessage: "Invalid VIN number format (must be 17 characters)",
            mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
            inputGroup: {
              append: [
                {
                  type: "button",
                  label: "Scan",
                  variant: "primary",
                  onClickHandler: "handleVinScan",
                }
              ]
            }
          },
          {
            key: "engineNr",
            type: "text",
            label: "Engine Number",
            placeholder: "Enter Engine Number",
            required: true,
            convert: "uppercase",
            validationMessage: "Engine number is required",
            minLength: 6,
            regexMessage: "Engine number must be at least 6 characters",
            mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
          },
          {
            key: "regNr",
            type: "text",
            label: "Registration Number",
            placeholder: "Enter Reg Number",
            required: true,
            convert: "uppercase",
            validationMessage: "Registration number is required",
            mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
          },
          {
            key: "stockNr",
            type: "text",
            label: "Stock Number",
            placeholder: "Enter Stock Number",
            convert: "uppercase",
          },
        ]
      },
      {
        label: "Leisure",
        subcategories: [
          {
            label: "Boats",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },              
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Petrol", "Diesel", "Hybrid", "Electric"],
              },
              {
                key: "hours",
                type: "number",
                label: "Engine Hours",
                placeholder: "Enter engine hours",
                required: true,
                validationMessage: "Engine hours are required",
              },
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              }, 
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },             
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              },
            ],
            subcategories: [
              { label: "Barge Boat" },
              { label: "Bass Boat" },
              { label: "Bow rider" },
              { label: "Cabin Boat" },
              { label: "Catamaran" },
              { label: "Centre Console Boat" },
              { label: "Cruiser" },
              { label: "Fish and Ski Boat" },
              { label: "Fishing Boat" },
              { label: "Inflatable" },
              { label: "Jet Ski" },
              { label: "Luxury Yacht" },
              { label: "Motorboat" },
              { label: "Outrigger Canoe" },
              { label: "Pilothouse" },
              { label: "Pontoon Boat" },
              { label: "Powerboat" },
              { label: "Riverboat" },
              { label: "Sail" },
              { label: "Semi-rigid" },
              { label: "Ski boat" },
              { label: "Wakeboard Boat" },
              { label: "Wakesurf Boat" },
              { label: "Yacht" }
            ]
          },
          {
            label: "Caravans & Trailers",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },
              {
                key: "axles",
                type: "number",
                label: "Number of Axles",
                placeholder: "Enter number of axles",
                required: true,
                validationMessage: "Number of axles is required",
              },
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              },
            ],
            subcategories: [
              { label: "Touring Caravan" },
              { label: "Static Caravan" },
              { label: "Off-road Caravan" },
              { label: "Pop-up Caravan" },
              { label: "Teardrop Caravan" },
              { label: "Tent Trailer" },
              { label: "Off-road Trailer" },
              { label: "Pop-up Trailer" },
              { label: "Venter Trailer" }
            ]
          }
        ]
      },
      {
        label: "Commercial",
        subcategories: [
          {
            label: "Trucks",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },              
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Petrol", "Diesel", "Hybrid", "Electric"],
              },
              {
                key: "transmission",
                type: "select",
                label: "Transmission",
                placeholder: "Select Transmission",
                required: true,
                validationMessage: "Transmission is required",
                options: ["Auto", "Manual"],
              },
              {
                key: "mileage",
                type: "number",
                label: "Mileage",
                placeholder: "Enter mileage",
                required: true,
                validationMessage: "Mileage is required",
              },
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "Bowser Truck" },
              { label: "Cage" },
              { label: "Car Transporter Truck" },
              { label: "Cattle Body" },
              { label: "Chassis Cab" },
              { label: "Cherry Picker Truck" },
              { label: "Compactor" },
              { label: "Concrete Mixer" },
              { label: "Concrete Pump" },
              { label: "Crane Truck" },
              { label: "Curtain Side Truck" },
              { label: "Diesel Tanker" },
              { label: "Dropside Truck" },
              { label: "Dump Truck" },
              { label: "Fire Fighting Unit" },
              { label: "Flatbed" },
              { label: "Honey Sucker" },
              { label: "Hooklift" },
              { label: "Insulated Body" },
              { label: "Mass Side" },
              { label: "Other Specialized" },
              { label: "Pantechnicon" },
              { label: "Petrol Tanker" },
              { label: "Refrigerated Body" },
              { label: "Roll Back" },
              { label: "Side Tipper" },
              { label: "Skip Loader" },
              { label: "Tanker" },
              { label: "Tautliner Truck" },
              { label: "Tipper Truck" },
              { label: "Truck Tractor" },
              { label: "Volume Body" }
            ]
          },
          {
            label: "Buses",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },              
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Petrol", "Diesel", "Hybrid", "Electric"],
              },
              {
                key: "transmission",
                type: "select",
                label: "Transmission",
                placeholder: "Select Transmission",
                required: true,
                validationMessage: "Transmission is required",
                options: ["Auto", "Manual"],
              },
              {
                key: "seats",
                type: "number",
                label: "Number of Seats",
                placeholder: "Enter number of seats",
                required: true,
                validationMessage: "Number of seats is required",
              },
              {
                key: "mileage",
                type: "number",
                label: "Mileage",
                placeholder: "Enter mileage",
                required: true,
                validationMessage: "Mileage is required",
              },
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "16 Seater" },
              { label: "22 Seater" },
              { label: "24 Seater" },
              { label: "25 Seater" },
              { label: "28 Seater" },
              { label: "30 Seater" },
              { label: "32 Seater" },
              { label: "40 Seater" },
              { label: "50 Seater" },
              { label: "60 Seater" },
              { label: "65 Seater" },
              { label: "70 Seater" },
              { label: "Luxury Bus" },
              { label: "Mini Bus" },
              { label: "Semi Luxury Bus" }
            ]
          },
          {
            label: "Cranes",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },                            
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Diesel", "Electric", "Hybrid"],
              },
              {
                key: "hours",
                type: "number",
                label: "Operating Hours",
                placeholder: "Enter operating hours",
                required: true,
                validationMessage: "Operating hours are required",
              },
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },              
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "All Terrain Crane" },
              { label: "Crawler Crane" },
              { label: "Mobile Crane" },
              { label: "Overhead Crane" },
              { label: "Rough Terrain Crane" },
              { label: "Self-Erecting Crane" },
              { label: "Sidelift Crane" },
              { label: "Tower Crane" },
              { label: "Tracked Crane" }
            ]
          },
          {
            label: "Dozers",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },                           
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Diesel", "Electric", "Hybrid"],
              },
              {
                key: "hours",
                type: "number",
                label: "Operating Hours",
                placeholder: "Enter operating hours",
                required: true,
                validationMessage: "Operating hours are required",
              }, 
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },              
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "Tracked Dozer" },
              { label: "Wheeled Dozer" }
            ]
          },
          {
            label: "Excavators",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },             
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Diesel", "Electric", "Hybrid"],
              },
              {
                key: "hours",
                type: "number",
                label: "Operating Hours",
                placeholder: "Enter operating hours",
                required: true,
                validationMessage: "Operating hours are required",
              },
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "Micro Excavator" },
              { label: "Midi Excavator" },
              { label: "Mini Excavator" },
              { label: "Track Excavator" },
              { label: "Wheeled Excavator" }
            ]
          },
          {
            label: "Forklifts",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "uppercase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "uppercase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },                           
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Petrol", "Diesel", "Electric", "LPG"],
              },
              {
                key: "transmission",
                type: "select",
                label: "Transmission",
                placeholder: "Select Transmission",
                required: true,
                validationMessage: "Transmission is required",
                options: ["Manual", "Automatic", "Hydrostatic"],
              },  
              {
                key: "hours",
                type: "number",
                label: "Operating Hours",
                placeholder: "Enter operating hours",
                required: true,
                validationMessage: "Operating hours are required",
              },            
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "Aerial Platform ForkLift" },
              { label: "All Terrain Forklift" },
              { label: "Cherry Picker Forklift" },
              { label: "Container Handler" },
              { label: "Counter Balanced Forklift" },
              { label: "Narrow Aisle Truck" },
              { label: "Reach Truck" },
              { label: "Side Loader" },
              { label: "Stacker" }
            ]
          },
          {
            label: "Graders",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },                           
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Diesel", "Electric", "Hybrid"],
              },              
              {
                key: "transmission",
                type: "select",
                label: "Transmission",
                placeholder: "Select Transmission",
                required: true,
                validationMessage: "Transmission is required",
                options: ["Manual", "Automatic", "Hydrostatic"],
              },
              {
                key: "hours",
                type: "number",
                label: "Operating Hours",
                placeholder: "Enter operating hours",
                required: true,
                validationMessage: "Operating hours are required",
              }, 
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
          },
          {
            label: "Loaders",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },            
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Diesel", "Electric", "Hybrid"],
              },
              {
                key: "transmission",
                type: "select",
                label: "Transmission",
                placeholder: "Select Transmission",
                required: true,
                validationMessage: "Transmission is required",
                options: ["Manual", "Automatic", "Hydrostatic"],
              },    
              {
                key: "hours",
                type: "number",
                label: "Operating Hours",
                placeholder: "Enter operating hours",
                required: true,
                validationMessage: "Operating hours are required",
              },          
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "Front end Loader" },
              { label: "Multi-terrain Loader" },
              { label: "Rough Terrain Loader" },
              { label: "Skid Steer Loader" },
              { label: "TLB" },
              { label: "Tracked Loader" },
              { label: "Wheeled Loader" }
            ]
          },
          {
            label: "Rollers",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },              
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Diesel", "Electric", "Hybrid"],
              },   
              {
                key: "hours",
                type: "number",
                label: "Operating Hours",
                placeholder: "Enter operating hours",
                required: true,
                validationMessage: "Operating hours are required",
              },           
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },              
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "Flat" },
              { label: "PadFoot" }
            ]
          },
          {
            label: "Tractors",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },
              {
                key: "fuelType",
                type: "select",
                label: "Fuel Type",
                placeholder: "Select Fuel Type",
                required: true,
                validationMessage: "Fuel type is required",
                options: ["Diesel", "Electric", "Hybrid"],
              },
              {
                key: "transmission",
                type: "select",
                label: "Transmission",
                placeholder: "Select Transmission",
                required: true,
                validationMessage: "Transmission is required",
                options: ["Manual", "Automatic", "Hydrostatic"],
              },
              {
                key: "hours",
                type: "number",
                label: "Operating Hours",
                placeholder: "Enter operating hours",
                required: true,
                validationMessage: "Operating hours are required",
              },
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              },
              {
                key: "engineNr",
                type: "text",
                label: "Engine Number",
                placeholder: "Enter Engine Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Engine number is required",
                minLength: 6,
                regexMessage: "Engine number must be at least 6 characters",
                mutedText: "The Engine number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "2WD" },
              { label: "4WD" },
              { label: "Tracked" }
            ]
          },
          {
            label: "Trailers",
            attributes: [
              {
                key: "year",
                type: "select",
                label: "Year",
                placeholder: "Select year",
                required: true,
                validationMessage: "Please select a year",
                options: ["Select Year", ...Array.from({ length: 54 }, (_, i) => 2024 - i)],
                onChangeHandler: "handleYear",
              },
              {
                key: "make",
                type: "text",
                label: "Make",
                placeholder: "Enter make",
                required: true,
                convert: "titlecase",
                validationMessage: "Make is required",
              },
              {
                key: "model",
                type: "text",
                label: "Model",
                placeholder: "Enter model",
                required: true,
                convert: "titlecase",
                validationMessage: "Model is required",
              },
              {
                key: "mmCode",
                type: "text",
                label: "MMCode",
                placeholder: "Not available",
                disabled: true,
              },
              {
                key: "axles",
                type: "number",
                label: "Number of Axles",
                placeholder: "Enter number of axles",
                required: true,
                validationMessage: "Number of axles is required",
              },                          
              {
                key: "colour",
                type: "select",
                label: "Colour",
                placeholder: "Select Colour",
                required: true,
                validationMessage: "Colour is required",
                optionsSource: "colors",
              },
              {
                key: "vinNr",
                type: "text",
                label: "VIN Number",
                placeholder: "Enter VIN Number",
                required: true,
                convert: "uppercase",
                validationMessage: "VIN number is required",
                validationRegex: /^[A-HJ-NPR-Z0-9]{17}$/,
                regexMessage: "Invalid VIN number format (must be 17 characters)",
                mutedText: "The VIN number is not publicly displayed and is only used for invoicing and documentation purposes.",
                inputGroup: {
                  append: [
                    {
                      type: "button",
                      label: "Scan",
                      variant: "primary",
                      onClickHandler: "handleVinScan",
                    }
                  ]
                }
              }, 
              {
                key: "regNr",
                type: "text",
                label: "Registration Number",
                placeholder: "Enter Reg Number",
                required: true,
                convert: "uppercase",
                validationMessage: "Registration number is required",
                mutedText: "The Reg number is not publicly displayed and is only used for invoicing and documentation purposes.",
              },
              {
                key: "stockNr",
                type: "text",
                label: "Stock Number",
                placeholder: "Enter Stock Number",
                convert: "uppercase",
              }
            ],
            subcategories: [
              { label: "Bale Trailer" },
              { label: "Bowser Trailer" },
              { label: "Box Trailer" },
              { label: "Brick Trailer" },
              { label: "Cage Body Trailer" },
              { label: "Car Transporter Trailer" },
              { label: "Cattle Trailer" },
              { label: "Curtain Side Trailer" },
              { label: "Dolly" },
              { label: "Drawbar Trailer" },
              { label: "Dropside Trailer" },
              { label: "Fire Fighting Trailer" },
              { label: "Flat Deck Trailer" },
              { label: "Folding Goose Neck Trailer" },
              { label: "Front Link Trailer" },
              { label: "High Speed Trailer" },
              { label: "Interlink Trailer" },
              { label: "Logging Trailer" },
              { label: "Lowbed Trailer" },
              { label: "Mass Sides Trailer" },
              { label: "Payloader Trailer" },
              { label: "Refrigerated Trailer" },
              { label: "Semi Trailer" },
              { label: "Skeletal Trailer" },
              { label: "Sloper Trailer" },
              { label: "Step Deck Trailer" },
              { label: "Super Link Trailer" },
              { label: "Tank Trailer" },
              { label: "Tautliner Trailer" },
              { label: "Tipper Trailer" }
            ]
          }
        ]
      }
    ]
  },
  Property: {
    subcategories: [
      'For Sale',
      'For Rent', 
      'Developments',
      'Repossessed',
      'Agencies & Agents'
    ]
  },
  Goods: {
    subcategories: [
      'Appliances',
      'Automotive Parts',
      'Baby & Kids',
      'Books & Games',
      'Clothing & Accessories', 
      'Electronics',
      'Furniture',
      'Health & Beauty',
      'Home & Garden',
      'Jewelry & Watches',
      'Musical Instruments',
      'Office Supplies',
      'Pet Supplies',
      'Sports & Fitness',
      'Tools & DIY',
      'Toys & Hobbies'
    ]
  }, 
  Rentals: {
    subcategories: [
      'Vehicles',
      'Equipment',
      'Crane',
      'Trucks', 
      'Grader',
      'Compactors'
    ]
  }
 };
 
 export default categories;