const countries = [
    { code: 'ZA', name: 'South Africa', ext: '+27' },
    { code: 'BW', name: 'Botswana', ext: '+267' },
    { code: 'NA', name: 'Namibia', ext: '+264' },
    { code: 'MZ', name: 'Mozambique', ext: '+258' },
    { code: 'ZW', name: 'Zimbabwe', ext: '+263' },
    { code: 'LS', name: 'Lesotho', ext: '+266' },    
    { code: 'AD', name: 'Andorra', ext: '+376' },
    { code: 'AE', name: 'United Arab Emirates', ext: '+971' },
    { code: 'AG', name: 'Antigua & Barbuda', ext: '+1-268' },
    { code: 'AI', name: 'Anguilla', ext: '+1-264' },
    { code: 'AL', name: 'Albania', ext: '+355' },
    { code: 'AM', name: 'Armenia', ext: '+374' },
    { code: 'AO', name: 'Angola', ext: '+244' },
    { code: 'AR', name: 'Argentina', ext: '+54' },
    { code: 'AS', name: 'American Samoa', ext: '+1-684' },
    { code: 'AT', name: 'Austria', ext: '+43' },
    { code: 'AU', name: 'Australia', ext: '+61' },
    { code: 'AW', name: 'Aruba', ext: '+297' },
    { code: 'AX', name: 'Åland Islands', ext: '+358-18' },
    { code: 'AZ', name: 'Azerbaijan', ext: '+994' },
    { code: 'BA', name: 'Bosnia and Herzegovina', ext: '+387' },
    { code: 'BB', name: 'Barbados', ext: '+1-246' },
    { code: 'BD', name: 'Bangladesh', ext: '+880' },
    { code: 'BE', name: 'Belgium', ext: '+32' },
    { code: 'BF', name: 'Burkina Faso', ext: '+226' },
    { code: 'BG', name: 'Bulgaria', ext: '+359' },
    { code: 'BH', name: 'Bahrain', ext: '+973' },
    { code: 'BI', name: 'Burundi', ext: '+257' },
    { code: 'BJ', name: 'Benin', ext: '+229' },
    { code: 'BL', name: 'Saint Barthélemy', ext: '+590' },
    { code: 'BM', name: 'Bermuda', ext: '+1-441' },
    { code: 'BN', name: 'Brunei', ext: '+673' },
    { code: 'BO', name: 'Bolivia', ext: '+591' },
    { code: 'BQ', name: 'Caribbean Netherlands', ext: '+599' },
    { code: 'BR', name: 'Brazil', ext: '+55' },
    { code: 'BS', name: 'Bahamas', ext: '+1-242' },    
    { code: 'BY', name: 'Belarus', ext: '+375' },
    { code: 'BZ', name: 'Belize', ext: '+501' },
    { code: 'CA', name: 'Canada', ext: '+1' },
    { code: 'CC', name: 'Cocos (Keeling) Islands', ext: '+61' },
    { code: 'CD', name: 'Democratic Republic of the Congo', ext: '+243' },
    { code: 'CF', name: 'Central African Republic', ext: '+236' },
    { code: 'CG', name: 'Republic of the Congo', ext: '+242' },
    { code: 'CH', name: 'Switzerland', ext: '+41' },
    { code: 'CI', name: "Côte d'Ivoire", ext: '+225' },
    { code: 'CK', name: 'Cook Islands', ext: '+682' },
    { code: 'CL', name: 'Chile', ext: '+56' },
    { code: 'CM', name: 'Cameroon', ext: '+237' },
    { code: 'CN', name: 'China', ext: '+86' },
    { code: 'CO', name: 'Colombia', ext: '+57' },
    { code: 'CR', name: 'Costa Rica', ext: '+506' },
    { code: 'CU', name: 'Cuba', ext: '+53' },
    { code: 'CV', name: 'Cape Verde', ext: '+238' },
    { code: 'CW', name: 'Curaçao', ext: '+599' },
    { code: 'CX', name: 'Christmas Island', ext: '+61' },
    { code: 'CY', name: 'Cyprus', ext: '+357' },
    { code: 'CZ', name: 'Czech Republic', ext: '+420' },
    { code: 'DE', name: 'Germany', ext: '+49' },
    { code: 'DJ', name: 'Djibouti', ext: '+253' },
    { code: 'DK', name: 'Denmark', ext: '+45' },
    { code: 'DM', name: 'Dominica', ext: '+1-767' },
    { code: 'DO', name: 'Dominican Republic', ext: '+1-809' },
    { code: 'DZ', name: 'Algeria', ext: '+213' },
    { code: 'EC', name: 'Ecuador', ext: '+593' },
    { code: 'EE', name: 'Estonia', ext: '+372' },
    { code: 'EG', name: 'Egypt', ext: '+20' },
    { code: 'EH', name: 'Western Sahara', ext: '+212' },
    { code: 'ER', name: 'Eritrea', ext: '+291' },
    { code: 'ES', name: 'Spain', ext: '+34' },
    { code: 'ET', name: 'Ethiopia', ext: '+251' },
    { code: 'FI', name: 'Finland', ext: '+358' },
    { code: 'FJ', name: 'Fiji', ext: '+679' },
    { code: 'FO', name: 'Faroe Islands', ext: '+298' },
    { code: 'FR', name: 'France', ext: '+33' },
    { code: 'GA', name: 'Gabon', ext: '+241' },
    { code: 'GB', name: 'United Kingdom', ext: '+44' },
    { code: 'GD', name: 'Grenada', ext: '+1-473' },
    { code: 'GE', name: 'Georgia', ext: '+995' },
    { code: 'GF', name: 'French Guiana', ext: '+594' },
    { code: 'GG', name: 'Guernsey', ext: '+44-1481' },
    { code: 'GH', name: 'Ghana', ext: '+233' },
    { code: 'GI', name: 'Gibraltar', ext: '+350' },
    { code: 'GL', name: 'Greenland', ext: '+299' },
    { code: 'GM', name: 'Gambia', ext: '+220' },
    { code: 'GN', name: 'Guinea', ext: '+224' },
    { code: 'GP', name: 'Guadeloupe', ext: '+590' },
    { code: 'GQ', name: 'Equatorial Guinea', ext: '+240' },
    { code: 'GR', name: 'Greece', ext: '+30' },
    { code: 'GT', name: 'Guatemala', ext: '+502' },
    { code: 'GU', name: 'Guam', ext: '+1-671' },
    { code: 'GW', name: 'Guinea-Bissau', ext: '+245' },
    { code: 'GY', name: 'Guyana', ext: '+592' },
    { code: 'HK', name: 'Hong Kong', ext: '+852' },
    { code: 'HN', name: 'Honduras', ext: '+504' },
    { code: 'HR', name: 'Croatia', ext: '+385' },
    { code: 'HT', name: 'Haiti', ext: '+509' },
    { code: 'HU', name: 'Hungary', ext: '+36' },
    { code: 'IC', name: 'Canary Islands', ext: '+34' },
    { code: 'ID', name: 'Indonesia', ext: '+62' },
    { code: 'IE', name: 'Ireland', ext: '+353' },
    { code: 'IL', name: 'Israel', ext: '+972' },
    { code: 'IM', name: 'Isle of Man', ext: '+44-1624' },
    { code: 'IR', name: 'Iran', ext: '+98' },
    { code: 'IS', name: 'Iceland', ext: '+354' },
    { code: 'IT', name: 'Italy', ext: '+39' },
    { code: 'JE', name: 'Jersey', ext: '+44-1534' },
    { code: 'JM', name: 'Jamaica', ext: '+1-876' },
    { code: 'JP', name: 'Japan', ext: '+81' },
    { code: 'KE', name: 'Kenya', ext: '+254' },
    { code: 'KM', name: 'Comoros', ext: '+269' },
    { code: 'KN', name: 'Saint Kitts & Nevis', ext: '+1-869' },
    { code: 'KR', name: 'South Korea', ext: '+82' },
    { code: 'KY', name: 'Cayman Islands', ext: '+1-345' },
    { code: 'LC', name: 'Saint Lucia', ext: '+1-758' },
    { code: 'LI', name: 'Liechtenstein', ext: '+423' },
    { code: 'LR', name: 'Liberia', ext: '+231' },    
    { code: 'LT', name: 'Lithuania', ext: '+370' },
    { code: 'LU', name: 'Luxembourg', ext: '+352' },
    { code: 'LV', name: 'Latvia', ext: '+371' },
    { code: 'LY', name: 'Libya', ext: '+218' },
    { code: 'MA', name: 'Morocco', ext: '+212' },
    { code: 'MC', name: 'Monaco', ext: '+377' },
    { code: 'MD', name: 'Moldova', ext: '+373' },
    { code: 'ME', name: 'Montenegro', ext: '+382' },
    { code: 'MF', name: 'Saint Martin', ext: '+590' },
    { code: 'MG', name: 'Madagascar', ext: '+261' },
    { code: 'MK', name: 'North Macedonia', ext: '+389' },
    { code: 'ML', name: 'Mali', ext: '+223' },
    { code: 'MQ', name: 'Martinique', ext: '+596' },
    { code: 'MR', name: 'Mauritania', ext: '+222' },
    { code: 'MS', name: 'Montserrat', ext: '+1-664' },
    { code: 'MT', name: 'Malta', ext: '+356' },
    { code: 'MW', name: 'Malawi', ext: '+265' },
    { code: 'MX', name: 'Mexico', ext: '+52' },
    { code: 'MY', name: 'Malaysia', ext: '+60' },   
    { code: 'NC', name: 'New Caledonia', ext: '+687' },
    { code: 'NE', name: 'Niger', ext: '+227' },
    { code: 'NG', name: 'Nigeria', ext: '+234' },
    { code: 'NI', name: 'Nicaragua', ext: '+505' },
    { code: 'NL', name: 'Netherlands', ext: '+31' },
    { code: 'NO', name: 'Norway', ext: '+47' },
    { code: 'NZ', name: 'New Zealand', ext: '+64' },
    { code: 'PA', name: 'Panama', ext: '+507' },
    { code: 'PE', name: 'Peru', ext: '+51' },
    { code: 'PH', name: 'Philippines', ext: '+63' },
    { code: 'PL', name: 'Poland', ext: '+48' },
    { code: 'PM', name: 'Saint Pierre & Miquelon', ext: '+508' },
    { code: 'PR', name: 'Puerto Rico', ext: '+1-787' },
    { code: 'PT', name: 'Portugal', ext: '+351' },
    { code: 'PY', name: 'Paraguay', ext: '+595' },
    { code: 'RE', name: 'Réunion', ext: '+262' },
    { code: 'RO', name: 'Romania', ext: '+40' },
    { code: 'RS', name: 'Serbia', ext: '+381' },
    { code: 'RU', name: 'Russia', ext: '+7' },
    { code: 'RW', name: 'Rwanda', ext: '+250' },
    { code: 'SC', name: 'Seychelles', ext: '+248' },
    { code: 'SD', name: 'Sudan', ext: '+249' },
    { code: 'SE', name: 'Sweden', ext: '+46' },
    { code: 'SG', name: 'Singapore', ext: '+65' },
    { code: 'SH', name: 'Saint Helena', ext: '+290' },
    { code: 'SI', name: 'Slovenia', ext: '+386' },
    { code: 'SJ', name: 'Svalbard & Jan Mayen', ext: '+47' },
    { code: 'SK', name: 'Slovakia', ext: '+421' },
    { code: 'SL', name: 'Sierra Leone', ext: '+232' },
    { code: 'SM', name: 'San Marino', ext: '+378' },
    { code: 'SN', name: 'Senegal', ext: '+221' },
    { code: 'SO', name: 'Somalia', ext: '+252' },
    { code: 'SR', name: 'Suriname', ext: '+597' },
    { code: 'SS', name: 'South Sudan', ext: '+211' },
    { code: 'ST', name: 'São Tomé & Príncipe', ext: '+239' },
    { code: 'SV', name: 'El Salvador', ext: '+503' },
    { code: 'SX', name: 'Sint Maarten', ext: '+1-721' },
    { code: 'SZ', name: 'Eswatini', ext: '+268' },
    { code: 'TC', name: 'Turks & Caicos Islands', ext: '+1-649' },
    { code: 'TD', name: 'Chad', ext: '+235' },
    { code: 'TG', name: 'Togo', ext: '+228' },
    { code: 'TH', name: 'Thailand', ext: '+66' },
    { code: 'TN', name: 'Tunisia', ext: '+216' },
    { code: 'TO', name: 'Tonga', ext: '+676' },
    { code: 'TR', name: 'Turkey', ext: '+90' },
    { code: 'TT', name: 'Trinidad & Tobago', ext: '+1-868' },
    { code: 'TW', name: 'Taiwan', ext: '+886' },
    { code: 'TZ', name: 'Tanzania', ext: '+255' },
    { code: 'UA', name: 'Ukraine', ext: '+380' },
    { code: 'UG', name: 'Uganda', ext: '+256' },
    { code: 'US', name: 'United States', ext: '+1' },
    { code: 'UY', name: 'Uruguay', ext: '+598' },
    { code: 'VA', name: 'Vatican City', ext: '+39-06' },
    { code: 'VC', name: 'Saint Vincent & Grenadines', ext: '+1-784' },
    { code: 'VE', name: 'Venezuela', ext: '+58' },
    { code: 'VG', name: 'British Virgin Islands', ext: '+1-284' },
    { code: 'VI', name: 'U.S. Virgin Islands', ext: '+1-340' },
    { code: 'VN', name: 'Vietnam', ext: '+84' },
    { code: 'VU', name: 'Vanuatu', ext: '+678' },
    { code: 'XK', name: 'Kosovo', ext: '+383' },
    { code: 'YT', name: 'Mayotte', ext: '+262' },    
    { code: 'ZM', name: 'Zambia', ext: '+260' }    
];

export default countries;